### PR TITLE
Sync posts

### PR DESCRIPTION
**Pull request by TimoTokki**
<dl>
<dt>
Update posts in <code>./site/_docs</code> by Merging jekyllrb
</dt>    
<dd>    
posts: used <code>git checkout master '.site/_docs' </code> to resolve coflicts
</dd>
</dl>

### CODE REVIEW

**Comment by TimoTokki** [comment]
I don\`t understand why there are so many commits.

Is it because I merged jekyll/master, so the commits were merged at the same time?

**Comment by xcatliu** [comment]
> Is it because I merged jekyll/master, so the commits were merged at the same time?

Yes

**Comment by xcatliu** [comment]
Successfully deployed, congratulations!

http://jekyllcn.com/docs/themes/

**Comment by xcatliu** [comment]
@TimoTokki Added you as a collaborator, you should have push access now.

**Comment by TimoTokki** [comment]
@xcatliu Thank you!

**Pull request merged**
